openapi: 3.0.0
info:
  title: accountsApi
  version: 1.0.0
  description: API to retrieve and update accounts.
servers:
  - url: /
paths:
  /accounts:
    get:
      description: Get a list of accounts.
      responses:
        200:
          description: Retrieved all accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/account'
        500:
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /accounts/{accountId}:
    put:
      description: Update an account.
      parameters:
        - in: path
          name: accountId
          description: Id of an account.
          required: true
          schema:
            type: integer
            example: 000150
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/account'
      responses:
        200:
          description: Account updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'  
        400:
          description: Bad request - account not valid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        500:
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    account:
      type: object
      properties:
        accountId:
          type: integer
          example: 000150
        accountHolder:
          type: string
          example: Bruce Adamson
        accountDept:
          type: string
          example: D11
    errorResponse:
      type: string
      example: Error message
